version: '3.2'

services:
  guacd:
    build:
      context: ./guacamole-guacd
    networks:
      - backend
    restart: always

  web:
    build:
      context: ./guacamole-web
    labels:
      traefik.host: "vnc"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:my.hostname.invalid"
      traefik.port: "9080"
      traefik.docker.network: traefik_traefik
      traefik.protocol: "http"
    networks:
      - traefik
      - backend
    restart: always
    links:
      - guacd
    volumes:
      - ./user-mapping.xml:/config/properties/user-mapping.xml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/translations/en.json"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  traefik:
    external:
      name: traefik_traefik
  backend:
    driver: bridge
