version: '3.2'

services:
  guacd:
    build:
      context: ./guacamole-guacd
    ports:
      - 4822
    networks:
      - backend
    restart: always

  web:
    build:
      context: ./guacamole-web
    labels:
      - "traefik.host=vnc"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:my.hostname.invalid"
      - "traefik.port=9080"
      - "traefik.docker.network=traefik_traefik"
      - "traefik.protocol=http"
    ports:
      - 9080
    networks:
      - backend
      - frontend
      - traefik
    restart: always
    volumes:
      ./user-mapping.xml:/config/properties/user-mapping.xml:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "https://my.hostname.invalid:443/"]
      interval: 10m30s
      timeout: 10s
      retries: 3

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
  traefik:
    external:
      name: traefik_traefik
